environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@latest
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
